### PR TITLE
Get pattern list fix for slower pixelblazes

### PR DESCRIPTION
**Pull request by pixxxie**
Fix for websocket timeout in `getPatternList()`, and cleanup of a `__pycache__` folder that the `.gitignore` file ought to have blocked.

### CODE REVIEW

**Comment by zranger1** [comment]
Good find!  It definitely happens on some of my Pixelblazes too. (Wish I knew why -- I've been meaning to bug Ben about that, and the fact that these PBs are sometimes super slow to load patterns.  It makes play lists mostly unusable.) 

One thing: Is there a way out of the loop
```python
while frame is None:  
            frame = self.ws_recv(True)
```
if the Pixelblaze disappears right at that moment?  

How long are your Pixelblazes taking, worst case?   Mine seem like about 3 or 4 seconds sometimes.   Maybe try changing
the timeout on that particular ws_recv() to something huge like:
```python
self.ws.settimeout(10)
 ```
then doing the read, then setting it back to the default if it hasn't blown up and caused an exception.  If the PB is gone for more than 10 seconds, somebody's gonna need to walk over and reset it!
```python                
self.ws.settimeout(self.default_recv_timeout)  
```

**Comment by pixxxie** [comment]
I've never timed it, but I didn't notice this particular problem before I slowed down the CPU speed (new in v3.24) so my first guess is that the Pixelblaze is taking longer to generate the pattern list than the basic timeout allows.  

You also mentioned slowness changing patterns; I have noticed that my v2 PBs change patterns about 100-150ms after I click a new pattern in the list, but with the v3s there is a noticeable delay -- sometimes 3 to 5 seconds -- between the click and when the pattern actually changes.

Anyway, back to the endless loop: I tried tripling the timeout to counteract the maximum CPU slowdown:
```
self.ws.settimeout(3 * self.default_recv_timeout)
frame = self.ws_recv(True)
self.ws.settimeout(self.default_recv_timeout)  
```
...and the read hasn't timed out yet in the few minutes I've been testing, so perhaps that's a good enough fix for now.  If I commit the above change into this branch will that be enough to go forward (I assume the merge will take care of overwriting the first attempt), or do I need to re-submit or delete-and-recreate the pull request?

**Comment by zranger1** [comment]
Awesome!  New commits will indeed  overwrite older ones.  Go ahead and commit and merge this, and I'll get it into pypi asap!  

It's reassuring that you're seeing the pattern load slowdown too.  Since none of the regular playlist user types seem to be complaining, I'd thought it was just because of some crazy thing I'd done with patterns.

**Review by zranger1 — APPROVED** [review]

**Comment by pixxxie** [comment]
Yes, the pattern-change delay is strange.  I had a quick look before dinner and didn't see anything unusual in the serial port debug output, but looking at the websocket traffic I thought I saw the PB closing the connection after each of the pattern changes which seemed rather impolite.  I'm in the midst of writing a parser to dump websocket packet captures so I'll take a more thorough look when that's finished.

**Comment by zranger1** [comment]
v0.9.6 live on pypi!

**Pull request merged**
